# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    filter_sets:

        # name our first filter set "my_min_up_scale_filter"
        squared_thumbnail_medium:
            filters:

                # use and setup the "upscale" filter
                thumbnail:

                    # input 1980x1280px -> output 3960x2560px
                    size: [250, 250]
                    mode : outbound
                    allow_upscale: true

        # name our first filter set "my_min_up_scale_filter"
        squared_thumbnail_small:
            filters:

                # use and setup the "upscale" filter
                thumbnail:

                    # input 1980x1280px -> output 3960x2560px
                    size: [200, 200]
                    mode : outbound
                    allow_upscale: true
                    
        squared_thumbnail_profile:
            filters:

                # use and setup the "upscale" filter
                thumbnail:

                    # input 1980x1280px -> output 3960x2560px
                    size: [45, 45]
                    mode : outbound
                    allow_upscale: true